config/routes.rb
Rails.application.routes.draw do

end
Rails.application.routes.draw do
 
  resources :ebooks
end

app/models/ebook.rb
class Ebook < ActiveRecord::Base
	validates :title, presence: true
	validates :publish_after, presence: true
	validates :published_at, presence: true
	has_attached_file :cover
	validates_attachment_presence :cover
	validates_attachment_content_type :cover, content_type: /\Aimage/
	has_attached_file :book
	validates_attachment_presence :book
	validates_attachment_content_type :book, content_type: "application/pdf"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ebooks_controller.rb
class EbooksController < ApplicationController

	def index
	    @ebooks = Ebook.all
	end

	def new
		@ebook = Ebook.new
	end


  	def create

  		@ebook = Ebook.new(ebook_params)

  		if @ebook.save
  			redirect_to @ebook
  		else
  			render 'new'
  		end		
 	end


 	 def edit
	    @ebook = Ebook.find(params[:id])
	 end

 	def show
    	@ebook = Ebook.find(params[:id])
 	 end

	def update
		 @ebook = Ebook.find(params[:id])
 
		  if @ebook.update(ebook_params)
		    redirect_to @ebook
		  else
		    render 'edit'
		  end
	end
	def destroy
   	
   	 @ebook = Ebook.find(params[:id])
    @ebook.destroy
 
    redirect_to @ebook
 	 end

 	private def ebook_params
 		params.require(:ebook).permit(:title,:published_at, :publish_after, :cover, :book)
 	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ebooks_helper.rb
module EbooksHelper
end

app/views/ebooks/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
</head>
<style type="text/css">
  body{
    position: relative;
  }
  img{
  	width: 70px;
  	height: 40px;
  }
  i{
  	font-size: 40px;
  }
</style>
<body>

<div class="container">
  <div class="row">
  <h2>E-Book Edit</h2>
    <%= link_to 'Back', ebooks_path %>

  
<%= form_for :ebook, url: ebook_path(@ebook), method: :patch do |f| %>

<% if @ebook.errors.any? %>
<div class="alert alert-danger alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
 
    <div id="error_explanation">
      <h6>
        <%= pluralize(@ebook.errors.count, "error") %> prohibited
        this ebook from being saved:
      </h6>
      <ul>
        <% @ebook.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
      <!-- <input type="email" class="form-control" id="email" placeholder="Enter email" name="email"> -->
    </div>
    <div class="form-group">
       <%= f.label :published_at %>
     <%= f.select :published_at, [['True',1],['False',0],@ebook.published_at] , include_blank: 'Please select'%>
    </div>

    <div class="6">
    <div class="form-group">
       <%= f.label :publish_after %>
    <%= f.text_field :publish_after, class: 'datetimepicker'  %>
    </div>
    </div>

    <div class="form-group">
    	  <%= image_tag @ebook.cover.url %>
    	</br>
       <%=  f.label :cover %>
    <%= f.file_field :cover  %>
    </div>
    <div class="form-group">
    <%= link_to  @ebook.book(:original, false) do %>
    		<i style="font-size: 40px;" class="fa fa-file-pdf-o"></i> 
<% end %>
    </br>
       <%= label_tag(:book, "Book:") %>
    <%= f.file_field :book  %>
    </div>
    <%= f.submit "Update" %>
  
    <!-- <button type="submit" class="btn btn-default">Submit</button> -->
  <% end %>
</div>
</div>
<script type="text/javascript">
            $(function () {
                $('.datetimepicker').datetimepicker({
        format: 'YYYY-MM-DD hh:mm'
    });
            });
        </script>
</body>
</html>

app/views/ebooks/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container">
  <h2>Listing of all Ebook Table</h2>
  <%=  link_to 'New Book', new_ebook_path, class: "btn btn-primary"%>
              
  <table class="table">
    <thead>
      <tr>
        <th>Title</th>
        <th>Cover</th>
        <th>Published</th>
        <th>Publish At</th>
        <th>Book</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
    	<% @ebooks.each do |ebook| %>
      <tr>
        <td><%= ebook.title %></td>
        <td><%= image_tag ebook.cover.url %></td>
        <td><%= ebook.published_at ? 'Published' : 'Not published' %></td>
        <td><%= ebook.publish_after %></td>
        <td>  <%= link_to "Download", ebook.book(:original, false) %></td>
        <td>   <%= link_to 'Show', ebook_path(ebook), class: "btn btn-success" %>
<!-- <button class="btn btn-danger"> -->
	<%= link_to 'Edit', edit_ebook_path(ebook), class: "btn btn-primary"%>
	<%= link_to 'Delete', ebook_path(ebook), method: :delete, data: { confirm: 'Are you sure you want to delete this item'} ,class: "btn btn-danger"%>
		
	</td>
<!-- </button> -->
      </tr>
        <% end %>
    </tbody>
  </table>
</div>

</body>
</html>

app/views/ebooks/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Bootstrap Example</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/css/bootstrap-datetimepicker.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
</head>
<style type="text/css">
  body{
    position: relative;
  }
</style>
<body>

<div class="container">
  <div class="row">
  <h2>E-Book Add</h2>
  
<%= form_for :ebook, url: ebooks_path  do |f| %>

<% if @ebook.errors.any? %>
<div class="alert alert-danger alert-dismissible">
  <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
 
    <div id="error_explanation">
      <h6>
        <%= pluralize(@ebook.errors.count, "error") %> prohibited
        this ebook from being saved:
      </h6>
      <ul>
        <% @ebook.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
    </div>
  <% end %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title %>
      <!-- <input type="email" class="form-control" id="email" placeholder="Enter email" name="email"> -->
    </div>
    <div class="form-group">
       <%= f.label :published_at %>
     <%= f.select :published_at, [['True',1],['False',0]] , include_blank: 'Please select' %>
    </div>

    <div class="6">
    <div class="form-group">
       <%= f.label :publish_after %>
    <%= f.text_field :publish_after, class: 'datetimepicker'  %>
    </div>
    </div>

    <div class="form-group">
       <%=  f.label :cover %>
    <%= f.file_field :cover  %>
    </div>
    <div class="form-group">
       <%= label_tag(:book, "Book:") %>
    <%= f.file_field :book  %>
    </div>
    <%= f.submit %>

    <!-- <button type="submit" class="btn btn-default">Submit</button> -->
  <% end %>
</div>
</div>
<script type="text/javascript">
            $(function () {
                $('.datetimepicker').datetimepicker({
        format: 'YYYY-MM-DD hh:mm'
    });
            });
        </script>
</body>
</html>

app/views/ebooks/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
 <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
</head>
<style type="text/css">
  body{
    position: relative;
  }
</style>
<body>
<div class="container">
	 <div id="blog" class="row"> 
                
                 <div class="col-sm-2 paddingTop20">
            <nav class="nav-sidebar">
                <ul class="nav">
                    <li class="active"><%= link_to 'New Book', new_ebook_path %>
</li>
                    
            </nav>
        </div>
                 <div class="col-md-10 blogShort">
                     <h1>  <%= @ebook.title %></h1>
                   <%= image_tag @ebook.cover.url %>
            	<br />         
            <%= link_to "Download", @ebook.book(:original, false) %>
                 </div>
                 
               <div class="col-md-12 gap10"></div>
             </div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ebook</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>